import Croll from '@/components/croll/Croll';
import Axios from 'axios';
import Head from 'next/head';

export default function Home({list}) {
  return (
    <>
      <Head>
        <title>sss</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-white dark:bg-gray-900">
        <div className="py-8 px-4 mx-auto max-w-screen-xl sm:py-16 lg:px-6">
            <div className="max-w-screen-md mb-8 lg:mb-16">
                <h2 className="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Designed for business teams like yours</h2>
                <p className="text-gray-500 sm:text-xl dark:text-gray-400">Here at Flowbite we focus on markets where technology, innovation, and capital can unlock long-term value and drive economic growth.</p>
            </div>
            <div className="space-y-8 md:grid md:grid-cols-2 lg:grid-cols-3 md:gap-12 md:space-y-0">

                <Croll crollList={list}/>

            </div>
        </div>
      </section>
    </>
  )
}


export async function getStaticProps(context) {

    console.log("ss",context)
    
    const API_URL = "http://localhost:3001/board";
    const res = await Axios.get(API_URL)
    const data = res.data;
    console.log(data);

    return {
        props: {
            list: data
        }
    }
}
